[project]
name = "analysis-service-core"
version = "1.11.1"
description = "a core library that different parts of the analysis service can borrow from"
authors = [
    {name = "Lawrence Borst",email = "laurens.s.borst@gmail.com"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.13"
dependencies = [
    "redis (>=7.1.0,<8.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "testcontainers[redis] (>=4.14.2,<5.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
packages = [
    {include = "analysis_service_core/src"},
    {include = "analysis_service_core/testing"},
]


[tool.black]
line-length = 88
target-version = ["py313"]
include = "analysis_service_core/.*\\.py$"


[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
src_paths = ["analysis_service_core"]


[tool.pytest.ini_options]
markers = [
    "e2e: marks tests as end-to-end (require Docker, slow)",
]


[tool.pydocstyle]
convention = "google"
match = ".*\\.py"
match-dir = "(?!tests|.venv|.mypy_cache|.pytest_cache|.tox|__pycache__).*"


[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
]
