[tox]
requires =
    tox>=4
env_list = py313, lint, format, docstrings, typecheck
skip_missing_interpreters = true

[testenv]
description = run tests
deps =
    pytest
    pytest-randomly
commands =
    pytest --strict-markers {posargs}
passenv =
    REDIS_HOST
    REDIS_PORT
    ECHOLALIA_DIR
    DATASETS_DIR

[testenv:lint]
description = Lint using flake8
skip_install = true
deps =
    flake8
commands =
    flake8 analysis_service_core

[testenv:format]
description = Check formatting using black, isort, autoflake
skip_install = true
deps =
    black
    isort
    autoflake
commands =
    black --check .
    isort --check-only .
    autoflake --check .

[testenv:docstrings]
description = Check docstrings using pydocstyle
skip_install = true
deps =
    pydocstyle
commands =
    pydocstyle

[testenv:typecheck]
description = Type-check using mypy
skip_install = true
deps =
    mypy
    pytest[mypy]
    redis[mypy]
commands =
    mypy analysis_service_core